[package]
name = "sha1"
version = "0.1.0"
authors = ["erer1243 <no email given>"]
edition = "2018"

[dev-dependencies]
criterion = "0.3"
mitsuhiko = { package = "sha1", version = "0.6" }
rustcrypto = { package = "sha-1", version = "0.9" }

[[bench]]
name = "bench"
harness = false
